### PR TITLE
Add links to tutorials and `npm install`

### PR DESCRIPTION
**Pull request by lelouchB**
Added links to Tutorials and `npm install` in  Getting Started

### CODE REVIEW

**Comment by colbyfayock** [comment]
this is great, thank you @lelouchB!

**Comment by lelouchB** [comment]
@colbyfayock I followed the tutorial on FreeCodeCamp, it was really nice. Thank you for that
If it's fine with you, I will be updating the Readme a bit more with the images and Gif's from your tutorial.
Thanks

**Comment by colbyfayock** [comment]
@lelouchB so happy to hear you enjoyed it :) that sounds amazing to me, thank you

you might also be interested to know it looks like i'll be doing a part 2 this week! https://twitter.com/colbyfayock/status/1281673416999870464

**Comment by lelouchB** [comment]
@colbyfayock Waiting for it.

**Pull request merged**
